# Generated by Django 3.1.3 on 2020-11-15 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=256)),
                ('owner_name', models.CharField(max_length=256)),
                ('document', models.CharField(db_index=True, max_length=128, unique=True)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coverage_area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
