# Generated by Django 3.1.3 on 2020-11-15 22:15

import json

from os import path

from django.db import migrations

from django.contrib.gis.geos import GEOSGeometry

def convert_data(apps, schema_editor):
    Trader = apps.get_model('geo', 'Trader')

    file_data = path.join(path.dirname(path.abspath(__file__)), 'pdvs.json')
    with open(file_data) as tmp:
        data = json.load(tmp)

    data = data.get('pdvs')
    for item in data:
        document = item.get('document')
        if Trader.objects.filter(document=document).exists():
            continue
        instance = Trader()
        instance.id = item.get('id')
        instance.trading_name = item.get('tradingName')
        instance.owner_name = item.get('ownerName')
        instance.document = document
        instance.address = GEOSGeometry(json.dumps(item.get('address')))
        instance.coverage_area = GEOSGeometry(json.dumps(item.get('coverageArea')))
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_data, migrations.RunPython.noop)
    ]
